<Project Sdk="Tomat.Terraria.ModLoader.Sdk/2.1.1">

    <!-- Import tModLoader mod properties -->
    <Import Project="/home/doug/.local/share/tml-build/versions/2026.6.3.4/tMLMod.targets"/>

    <!-- General -->
    <PropertyGroup>
        <AssemblyName>TheExtraordinaryAdditions</AssemblyName>
        <Configurations>Debug;Release</Configurations>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <Nullable>disable</Nullable>
        <LangVersion>latest</LangVersion>
        <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
        <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
        <TargetFramework>net8.0</TargetFramework>
        <TmlVersion>stable</TmlVersion>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="**/*.fx"/>
        <None Include="**/*.fx"/>
    </ItemGroup>

    <!-- References -->
    <ItemGroup>
        <Reference Include="DAYBREAK">
            <HintPath>lib\Daybreak_2.4.0.dll</HintPath>
        </Reference>
        <Reference Include="SubworldLibrary">
            <HintPath>lib\SubworldLibrary.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Update="tModLoader.CodeAssist" Version="0.1.5"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Microsoft.CodeAnalysis">
            <HintPath
            >..\..\.nuget\packages\microsoft.codeanalysis.common\4.11.0\lib\netstandard2.0\Microsoft.CodeAnalysis.dll
            </HintPath>
        </Reference>
        <Content Include="TEA.Generators\TEA.Generators.csproj"/>
        <ProjectReference
            Include="../TheExtraordinaryAdditions/TEA.Generators/TEA.Generators.csproj"
            OutputItemType="Analyzer"
            ReferenceOutputAssembly="false"
        />
    </ItemGroup>

</Project>
