global using Microsoft.Xna.Framework;
global using TheExtraordinaryAdditions.Assets;
global using TheExtraordinaryAdditions.Common.Particles.Particle;
global using static TheExtraordinaryAdditions.Core.Utilities.CoreUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.CollisionUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.MathUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.PrimitiveUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.TileUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.SpriteBatchUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.SeekingUtils;
global using RotatedRectangle = TheExtraordinaryAdditions.Core.DataStructures.RotatedRectangle;
global using SystemVector2 = System.Numerics.Vector2;
