global using Microsoft.Xna.Framework;
global using TheExtraordinaryAdditions.Assets;
global using TheExtraordinaryAdditions.Core.Graphics.Particles;
global using static TheExtraordinaryAdditions.Core.Utilities.Animators;
global using static TheExtraordinaryAdditions.Core.Utilities.CoreUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.CollisionUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.MathUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.PrimitiveUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.TileUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.SpriteBatchUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.SeekingUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.PlayerUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.ItemUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.ProjectileUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.NPCUtils;
global using static TheExtraordinaryAdditions.Core.Utilities.EntityUtils;
global using RotatedRectangle = TheExtraordinaryAdditions.Core.DataStructures.RotatedRectangle;
global using SystemVector2 = System.Numerics.Vector2;
global using SystemVector3 = System.Numerics.Vector3;
