using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace TheExtraordinaryAdditions.TEA.Generators
{
    [Generator]
    public sealed class AssetGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<AdditionalText> assetFiles =
                context.AdditionalTextsProvider.Where(static f =>
                    f.Path.Contains("Assets", StringComparison.OrdinalIgnoreCase));

            context.RegisterSourceOutput(assetFiles.Collect(), GenerateRegistries);
        }

        private static void GenerateRegistries(SourceProductionContext context, ImmutableArray<AdditionalText> files)
        {
            if (files.IsDefaultOrEmpty)
                return;

            Log(context, "starting to generate asset registry...");
            StringBuilder sb = new();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Microsoft.Xna.Framework.Graphics;");
            sb.AppendLine("using TheExtraordinaryAdditions.Assets;");
            sb.AppendLine("using ReLogic.Content;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.IO;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using Terraria;");
            sb.AppendLine("using Terraria.Audio;");
            sb.AppendLine("using Terraria.ModLoader;");
            sb.AppendLine("using TheExtraordinaryAdditions.Core.Graphics.Resources;");

            sb.AppendLine("public static partial class AssetRegistry");

            sb.AppendLine("{");

            List<AdditionalText> textures = files.Where(f => IsTextureFile(f.Path)).ToList();
            if (textures.Count > 0)
            {
                sb.AppendLine("\tpublic static class GennedTextures");
                sb.AppendLine("\t{");

                foreach (AdditionalText file in textures)
                {
                    string propertyName = GetSafePropertyName(file.Path);
                    string relativePath = GetRelativeAssetPath(file.Path);
                    string texturePath = Path.ChangeExtension(relativePath.Replace("\\", "/"), null);
                    sb.AppendLine(
                        $"\t\tpublic static LazyAsset<Texture2D> {propertyName} {{ get; }} = LazyAsset<Texture2D>.FromPath(\"TheExtraordinaryAdditions/{texturePath}\");");
                }

                sb.AppendLine("\t}");
            }

            sb.AppendLine();

            List<AdditionalText> shaders = files.Where(f => IsShaderFile(f.Path)).ToList();
            if (shaders.Count > 0)
            {
                sb.AppendLine("\tpublic static class GennedShaders");
                sb.AppendLine("\t{");

                sb.AppendLine("\t\tpublic static readonly Dictionary<string, ManagedShader> Shaders = [];");
                sb.AppendLine(
                    "\t\tpublic static void SetShader(string name, Ref<Effect> newShaderData) => Shaders[name] = new(name, newShaderData);");
                sb.AppendLine("\t\tpublic static readonly Dictionary<string, ManagedScreenShader> Filters = [];");
                sb.AppendLine(
                    "\t\tpublic static void SetFilter(string name, Ref<Effect> newShaderData) => Filters[name] = new(newShaderData);");
                sb.AppendLine("\t\tpublic static void LoadShaders(Mod mod)");
                sb.AppendLine("\t\t{");

                sb.AppendLine("\t\t\tList<string> fileNames = mod.GetFileNames();");
                sb.AppendLine("\t\t\tif (fileNames is null)");
                sb.AppendLine("\t\t\t\treturn;");

                sb.AppendLine(
                    "\t\t\tIEnumerable<string> shaderLoadPaths = fileNames.Where(path => path.Contains(\"AutoloadedEffects/Shaders\") && !path.Contains(\"Compiler/\") &&(path.Contains(\".xnb\") || path.Contains(\".fxc\")));");
                sb.AppendLine("\t\t\tforeach (string path in shaderLoadPaths)");
                sb.AppendLine("\t\t\t{");
                sb.AppendLine("\t\t\t\tstring shaderName = Path.GetFileNameWithoutExtension(path);");
                sb.AppendLine(
                    "\t\t\t\tstring clearedPath = Path.Combine(Path.GetDirectoryName(path), shaderName).Replace($\"{mod.Name}.\", string.Empty).Replace(@\"\\\", @\"/\");");
                sb.AppendLine(
                    "\t\t\t\tRef<Effect> shader = new(mod.Assets.Request<Effect>(clearedPath, AssetRequestMode.ImmediateLoad).Value);");
                sb.AppendLine("\t\t\t\tSetShader(shaderName, shader);");
                sb.AppendLine("\t\t\t}");
                sb.AppendLine(
                    "\t\t\tIEnumerable<string> filterLoadPaths = fileNames.Where(path => path.Contains(\"AutoloadedEffects/Filters\") && !path.Contains(\"Compiler/\") &&(path.Contains(\".xnb\") || path.Contains(\".fxc\")));");
                sb.AppendLine("\t\t\tforeach (string path in filterLoadPaths)");
                sb.AppendLine("\t\t\t{");
                sb.AppendLine("\t\t\t\tstring filterName = Path.GetFileNameWithoutExtension(path);");
                sb.AppendLine(
                    "\t\t\t\tstring clearedPath = Path.Combine(Path.GetDirectoryName(path), filterName).Replace($\"{mod.Name}.\", string.Empty).Replace(@\"\\\", @\"/\");");
                sb.AppendLine(
                    "\t\t\t\tRef<Effect> filter = new(mod.Assets.Request<Effect>(clearedPath, AssetRequestMode.ImmediateLoad).Value);");
                sb.AppendLine("\t\t\t\tSetFilter(filterName, filter);");
                sb.AppendLine("\t\t\t}");

                sb.AppendLine("\t\t}");

                foreach (AdditionalText file in shaders.Where(f => f.Path.Contains("Shaders")))
                {
                    string propertyName = GetSafePropertyName(file.Path);

                    sb.AppendLine(
                        $"\t\tpublic static ManagedShader {propertyName} {{ get {{ return Shaders.TryGetValue(\"{propertyName}\", out ManagedShader value) ? value : null; }} }}");
                }

                sb.AppendLine();

                sb.AppendLine("\t\tpublic static class Screen");
                sb.AppendLine("\t\t{");
                foreach (AdditionalText file in shaders.Where(f => f.Path.Contains("Filters")))
                {
                    string propertyName = GetSafePropertyName(file.Path);

                    sb.AppendLine(
                        $"\t\t\tpublic static ManagedScreenShader {propertyName} {{ get {{ return Filters.TryGetValue(\"{propertyName}\", out ManagedScreenShader value) ? value : null; }} }}");
                }

                sb.AppendLine("\t\t}");

                sb.AppendLine("\t}");
            }

            sb.AppendLine();

            List<AdditionalText> sounds = files.Where(f => IsSoundFile(f.Path)).ToList();
            if (sounds.Count > 0)
            {
                sb.AppendLine("\tpublic static class GennedSounds");
                sb.AppendLine("\t{");

                foreach (AdditionalText file in sounds.Where(f => !f.Path.Contains("NotMusic")))
                {
                    string propertyName = GetSafePropertyName(file.Path);
                    string relativePath = GetRelativeAssetPath(file.Path);
                    string soundPath = Path.ChangeExtension(relativePath.Replace("\\", "/"), null);
                    sb.AppendLine(
                        $"\t\tpublic static SoundStyle {propertyName} {{ get; }} = new SoundStyle(\"TheExtraordinaryAdditions/{soundPath}\", SoundType.Sound);");
                }

                sb.AppendLine("\t\tpublic static class Music");
                sb.AppendLine("\t\t{");
                foreach (AdditionalText file in sounds.Where(f => f.Path.Contains("NotMusic")))
                {
                    string propertyName = GetSafePropertyName(file.Path);
                    string relativePath = GetRelativeAssetPath(file.Path);
                    string soundPath = Path.ChangeExtension(relativePath.Replace("\\", "/"), null);
                    sb.AppendLine(
                        $"\t\t\tpublic static SoundStyle {propertyName} {{ get; }} = new SoundStyle(\"{soundPath}\", SoundType.Music);");
                }

                sb.AppendLine("\t\t}");

                sb.AppendLine("\t}");
            }

            sb.AppendLine("}");

            context.AddSource("AssetRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            Log(context, "done!");
        }

        private static bool IsTextureFile(string path) => path.EndsWith(".png", StringComparison.OrdinalIgnoreCase);
        private static bool IsShaderFile(string path) => path.EndsWith(".fxc", StringComparison.OrdinalIgnoreCase);

        private static bool IsSoundFile(string path) => path.EndsWith(".wav", StringComparison.OrdinalIgnoreCase) ||
                                                        path.EndsWith(".ogg", StringComparison.OrdinalIgnoreCase) ||
                                                        path.EndsWith(".mp3", StringComparison.OrdinalIgnoreCase);

        private static string GetSafePropertyName(string path)
        {
            string name = Path.GetFileNameWithoutExtension(path);

            name = name.Replace(" ", "_")
                .Replace("-", "_")
                .Replace(".", "_");

            if (char.IsDigit(name[0]))
                name = "_" + name;

            return name;
        }

        private static string GetRelativeAssetPath(string fullPath)
        {
            int assetsIndex = fullPath.LastIndexOf("Assets", StringComparison.OrdinalIgnoreCase);
            return assetsIndex >= 0
                ? fullPath.Substring(assetsIndex).Replace("\\", "/")
                : fullPath;
        }

        private static void Log(SourceProductionContext context, string message)
        {
            var descriptor = new DiagnosticDescriptor(
                id: "GEN001",
                title: "Generator Info",
                messageFormat: message,
                category: "SourceGenerator",
                defaultSeverity: DiagnosticSeverity.Info,
                isEnabledByDefault: true
            );
            var diagnostic = Diagnostic.Create(descriptor, Location.None);
            context.ReportDiagnostic(diagnostic);
        }
    }
}
